# Generated by Django 4.1.4 on 2022-12-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hck', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, null=True)),
                ('symptoms', models.CharField(choices=[('SELECT', 'SELECT'), ('Discomfort in stomach,Digestive Disorders', 'Discomfort in stomach,Digestive Disorders'), ('Chest Pain', 'Chest Pain'), ('X-Ray', 'X-Ray'), ('Injury,Fracture', 'Injury,Fracture'), ('Problem in Eyes', 'Problem in Eyes'), ('Depression,Mental Health', 'Depression,Mental Health'), ('Skin Problem', 'Skin Problem'), ('Ear,Nose or Throat Issues', 'Ear,Nose or Throat Issues'), ('Kidney Disease', 'Kidney Disease'), ('ToothCheck', 'ToothCheck')], default='SELECT', max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='clinic_website',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(choices=[('SELECT', 'SELECT'), ('Gastroenterology', 'Gastroenterology(Discomfort in stomach,Digestive Disorders)'), ('Cardiography', 'Cardiography(Chest Pain)'), ('Radiology', 'Radiology(X-Ray)'), ('Orthopedics', 'Orthopedics(Injury,Fracture)'), ('Opthalmology', 'Opthalmology(Problem in Eyes)'), ('Psychiatry', 'Psychiatry(Depression,Mental Health)'), ('Dermatology', 'Dermatology(Skin Problem)'), ('Otolaryngologist', 'Otolaryngologist(Ear,Nose or Throat Issues)'), ('Nephrology', 'Nephrology(Kidney Disease)'), ('Dentist', 'Dentist(ToothCheck)')], default='--', max_length=200),
        ),
    ]
